---
roles:
  - luizgavalda.aur
  - geerlingguy.dotfiles

collections:
  - name: community.general
    version: 8.2.0
    source: https://galaxy.ansible.com

  - name: geerlingguy.mac
    version: 2.1.3
    source: https://galaxy.ansible.com
