---
- name: Install yay packages.
  aur:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    use: yay
  with_items: "{{ yay_packages }}"
  become: no

- name: Install yay gnome packages.
  aur:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    use: yay
  with_items: "{{ yay_gnome_packages }}"
  become: no

- name: Install yay kde packages.
  aur:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    use: yay
  with_items: "{{ yay_kde_packages }}"
  become: no